"""add project management data model

Revision ID: 287d58af1aa4
Revises: f7f95a9cd9c4
Create Date: 2025-11-21 11:27:06.799195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287d58af1aa4'
down_revision: Union[str, Sequence[str], None] = 'f7f95a9cd9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_table('assumptions',
    sa.Column('assumption_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('assumption_id')
    )
    op.create_index(op.f('ix_assumptions_assumption_id'), 'assumptions', ['assumption_id'], unique=False)
    op.create_table('conversation_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=20), nullable=True),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_conversation_logs_log_id'), 'conversation_logs', ['log_id'], unique=False)
    op.create_table('project_inputs',
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('raw_audio_path', sa.Text(), nullable=True),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('cleaned_transcript', sa.Text(), nullable=True),
    sa.Column('final_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('input_id')
    )
    op.create_index(op.f('ix_project_inputs_input_id'), 'project_inputs', ['input_id'], unique=False)
    op.create_table('project_intents',
    sa.Column('intent_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('deliverables', sa.Text(), nullable=True),
    sa.Column('timeline_hints', sa.Text(), nullable=True),
    sa.Column('extracted_goals', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('intent_id')
    )
    op.create_index(op.f('ix_project_intents_intent_id'), 'project_intents', ['intent_id'], unique=False)
    op.create_table('project_versions',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_project_versions_version_id'), 'project_versions', ['version_id'], unique=False)
    op.create_table('risks',
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('likelihood', sa.String(length=20), nullable=True),
    sa.Column('impact', sa.String(length=20), nullable=True),
    sa.Column('mitigation_strategy', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('risk_id')
    )
    op.create_index(op.f('ix_risks_risk_id'), 'risks', ['risk_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scenario_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_start_date', sa.Date(), nullable=True),
    sa.Column('estimated_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_index(op.f('ix_scenarios_scenario_id'), 'scenarios', ['scenario_id'], unique=False)
    op.create_table('milestones',
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('estimated_start_date', sa.Date(), nullable=True),
    sa.Column('estimated_end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('milestone_id')
    )
    op.create_index(op.f('ix_milestones_milestone_id'), 'milestones', ['milestone_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_dependencies_id'), 'task_dependencies', ['id'], unique=False)
    op.add_column('tasks', sa.Column('milestone_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('scenario_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('duration_days', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('estimated_start_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('estimated_end_date', sa.Date(), nullable=True))
    # Add critical_path_flag as nullable first, set default values, then make non-nullable
    op.add_column('tasks', sa.Column('critical_path_flag', sa.Boolean(), nullable=True))
    op.execute("UPDATE tasks SET critical_path_flag = FALSE WHERE critical_path_flag IS NULL")
    op.alter_column('tasks', 'critical_path_flag', nullable=False, server_default=sa.false())
    op.add_column('tasks', sa.Column('order_index', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'scenarios', ['scenario_id'], ['scenario_id'])
    op.create_foreign_key(None, 'tasks', 'milestones', ['milestone_id'], ['milestone_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'order_index')
    op.drop_column('tasks', 'critical_path_flag')
    op.drop_column('tasks', 'estimated_end_date')
    op.drop_column('tasks', 'estimated_start_date')
    op.drop_column('tasks', 'duration_days')
    op.drop_column('tasks', 'scenario_id')
    op.drop_column('tasks', 'milestone_id')
    op.drop_index(op.f('ix_task_dependencies_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_milestones_milestone_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_scenarios_scenario_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_risks_risk_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_project_versions_version_id'), table_name='project_versions')
    op.drop_table('project_versions')
    op.drop_index(op.f('ix_project_intents_intent_id'), table_name='project_intents')
    op.drop_table('project_intents')
    op.drop_index(op.f('ix_project_inputs_input_id'), table_name='project_inputs')
    op.drop_table('project_inputs')
    op.drop_index(op.f('ix_conversation_logs_log_id'), table_name='conversation_logs')
    op.drop_table('conversation_logs')
    op.drop_index(op.f('ix_assumptions_assumption_id'), table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
