"""refactor_project_model_properties_jsonb

Revision ID: 307ba515e774
Revises: c38b7aac933d
Create Date: 2026-02-16 20:15:44.696299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '307ba515e774'
down_revision: Union[str, Sequence[str], None] = 'c38b7aac933d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('properties', sa.JSON(), server_default='{}', nullable=False))
    op.drop_column('projects', 'external_url')
    op.drop_column('projects', 'source')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'external_id')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'project_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('status', postgresql.ENUM('draft', 'planning', 'active', 'completed', 'archived', 'backlog', name='projectstatus'), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('source', postgresql.ENUM('native', 'jira', 'linear', 'github', name='projectsource'), server_default=sa.text("'native'::projectsource"), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('external_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('projects', 'properties')
    # ### end Alembic commands ###
