"""remove scenarios add project milestones and tasks

Revision ID: 314ed1945e1f
Revises: 7be0fbad9da5
Create Date: 2026-04-05 16:33:55.308281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '314ed1945e1f'
down_revision: Union[str, Sequence[str], None] = '7be0fbad9da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('project_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('milestones_scenario_id_fkey'), 'milestones', type_='foreignkey')
    op.create_foreign_key(None, 'milestones', 'projects', ['project_id'], ['project_id'])
    op.drop_column('milestones', 'scenario_id')
    op.add_column('tasks', sa.Column('project_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('tasks_scenario_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['project_id'])
    op.drop_column('tasks', 'scenario_id')
    op.drop_index(op.f('ix_scenarios_scenario_id'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scenario_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estimated_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('estimated_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('scenarios_project_id_fkey')),
    sa.PrimaryKeyConstraint('scenario_id', name=op.f('scenarios_pkey'))
    )
    op.create_index(op.f('ix_scenarios_scenario_id'), 'scenarios', ['scenario_id'], unique=False)
    op.add_column('tasks', sa.Column('scenario_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_scenario_id_fkey'), 'tasks', 'scenarios', ['scenario_id'], ['scenario_id'])
    op.drop_column('tasks', 'project_id')
    op.add_column('milestones', sa.Column('scenario_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.create_foreign_key(op.f('milestones_scenario_id_fkey'), 'milestones', 'scenarios', ['scenario_id'], ['scenario_id'])
    op.drop_column('milestones', 'project_id')
    # ### end Alembic commands ###
