"""migrate_properties_to_separate_table

Revision ID: 7be0fbad9da5
Revises: c1a2b3d4e5f6
Create Date: 2026-04-04 20:44:40.237523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7be0fbad9da5'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    
    # Data migration: Copy existing properties to the new table
    op.execute(
        """
        INSERT INTO properties (entity_type, entity_id, data)
        SELECT 'project', project_id, properties
        FROM projects
        WHERE properties IS NOT NULL AND properties::text != '{}'::text
        """
    )
    
    op.drop_column('projects', 'properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    
    # Data migration: Copy properties back from the separate table
    op.execute(
        """
        UPDATE projects
        SET properties = p.data
        FROM properties p
        WHERE p.entity_type = 'project' AND p.entity_id = projects.project_id
        """
    )
    
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
