"""Add workspace and team models

Revision ID: 8605203d04d7
Revises: f0ae55eaf85d
Create Date: 2026-04-13 09:49:39.219362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8605203d04d7'
down_revision: Union[str, Sequence[str], None] = 'f0ae55eaf85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('metadata_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='invite_role_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', name='invite_status_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pending_invite_email_workspace', 'invites', ['email', 'workspace_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index(op.f('ix_invites_id'), 'invites', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='workspace_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_user_workspace')
    )
    op.create_index(op.f('ix_workspace_memberships_id'), 'workspace_memberships', ['id'], unique=False)
    op.create_table('team_memberships',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_user_team')
    )
    op.create_index(op.f('ix_team_memberships_id'), 'team_memberships', ['id'], unique=False)
    
    # Add team_id as nullable first
    op.add_column('projects', sa.Column('team_id', sa.BigInteger(), nullable=True))
    
    # Data migration: create a default workspace and team for existing projects
    connection = op.get_bind()
    
    # Check if there are any users
    users = connection.execute(sa.text("SELECT id FROM users LIMIT 1")).fetchall()
    if users:
        # We have users, maybe we have projects
        # Let's create a default workspace and team for each user who has projects
        # (or just one global for all if it's easier, let's do per-user to be safe)
        
        # Get all users who have projects
        users_with_projects = connection.execute(sa.text("SELECT DISTINCT user_id FROM projects")).fetchall()
        
        for user_row in users_with_projects:
            uid = user_row[0]
            # Create Workspace
            connection.execute(sa.text(f"INSERT INTO workspaces (name, owner_id, created_by, created_at) VALUES ('My Workspace', {uid}, {uid}, NOW())"))
            workspace_id = connection.execute(sa.text("SELECT id FROM workspaces ORDER BY id DESC LIMIT 1")).scalar()
            
            # Create Workspace Membership
            connection.execute(sa.text(f"INSERT INTO workspace_memberships (user_id, workspace_id, role, created_at) VALUES ({uid}, {workspace_id}, 'ADMIN', NOW())"))
            
            # Create Team
            connection.execute(sa.text(f"INSERT INTO teams (name, workspace_id, is_default, created_at) VALUES ('General', {workspace_id}, true, NOW())"))
            team_id = connection.execute(sa.text("SELECT id FROM teams ORDER BY id DESC LIMIT 1")).scalar()
            
            # Create Team Membership
            connection.execute(sa.text(f"INSERT INTO team_memberships (user_id, team_id, created_at) VALUES ({uid}, {team_id}, NOW())"))
            
            # Assign team_id to projects for this user
            connection.execute(sa.text(f"UPDATE projects SET team_id = {team_id} WHERE user_id = {uid}"))
            
    # Now make team_id non-nullable
    op.alter_column('projects', 'team_id', nullable=False)
    
    op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'teams', ['team_id'], ['id'])
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['id'])
    op.drop_column('projects', 'team_id')
    op.drop_index(op.f('ix_team_memberships_id'), table_name='team_memberships')
    op.drop_table('team_memberships')
    op.drop_index(op.f('ix_workspace_memberships_id'), table_name='workspace_memberships')
    op.drop_table('workspace_memberships')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_invites_id'), table_name='invites')
    op.drop_index('idx_pending_invite_email_workspace', table_name='invites', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('invites')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
