"""upgrade_project_schema

Revision ID: 90e0fda055ea
Revises: aea2621cbd36
Create Date: 2026-01-12 21:41:46.697246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e0fda055ea'
down_revision: Union[str, Sequence[str], None] = 'aea2621cbd36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('source', sa.String(length=50), nullable=False, server_default='native'))
    op.add_column('projects', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('external_url', sa.String(length=512), nullable=True))
    op.add_column('projects', sa.Column('integration_metadata', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('resources', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('milestones', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('target_date', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('labels', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('teams', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('stats', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('lead_id', sa.BigInteger(), nullable=True))
    op.alter_column('projects', 'purpose',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='to_json(purpose)')
    op.alter_column('projects', 'objectives',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='to_json(objectives)')
    op.alter_column('projects', 'deliverables',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='to_json(deliverables)')
    op.alter_column('projects', 'scope',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='to_json(scope)')
    op.alter_column('projects', 'timeline',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='to_json(timeline)')
    op.alter_column('projects', 'budget',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='to_json(budget)')
    op.alter_column('projects', 'stakeholders',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='to_json(stakeholders)')
    op.alter_column('projects', 'team_members',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='to_json(team_members)')
    op.create_foreign_key(None, 'projects', 'users', ['lead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'team_members',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'stakeholders',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'budget',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'timeline',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'scope',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'deliverables',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'objectives',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'purpose',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('projects', 'lead_id')
    op.drop_column('projects', 'stats')
    op.drop_column('projects', 'teams')
    op.drop_column('projects', 'labels')
    op.drop_column('projects', 'target_date')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'milestones')
    op.drop_column('projects', 'resources')
    op.drop_column('projects', 'integration_metadata')
    op.drop_column('projects', 'external_url')
    op.drop_column('projects', 'external_id')
    op.drop_column('projects', 'source')
    # ### end Alembic commands ###
