"""use_enums_for_project_fields

Revision ID: becefec2b22a
Revises: 90e0fda055ea
Create Date: 2026-01-12 21:52:42.663346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'becefec2b22a'
down_revision: Union[str, Sequence[str], None] = '90e0fda055ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enums first
    # Drop types if they exist (handling cleanup from failed runs)
    op.execute("DROP TYPE IF EXISTS projectstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS projectsource CASCADE")
    op.execute("DROP TYPE IF EXISTS projectpriority CASCADE")

    project_status_enum = sa.Enum('draft', 'planning', 'active', 'completed', 'archived', 'backlog', name='projectstatus')
    project_source_enum = sa.Enum('native', 'jira', 'linear', 'github', name='projectsource')
    project_priority_enum = sa.Enum('urgent', 'high', 'medium', 'low', 'none', name='projectpriority')
    
    project_status_enum.create(op.get_bind(), checkfirst=True)
    project_source_enum.create(op.get_bind(), checkfirst=True)
    project_priority_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=project_status_enum,
               existing_nullable=False,
               postgresql_using='status::projectstatus')
               
    # Drop old default first to allow type change
    op.execute("ALTER TABLE projects ALTER COLUMN source DROP DEFAULT")
    
    op.alter_column('projects', 'source',
               existing_type=sa.VARCHAR(length=50),
               type_=project_source_enum,
               existing_nullable=False,
               server_default=sa.text("'native'::projectsource"),
               existing_server_default=sa.text("'native'::character varying"),
               postgresql_using='source::projectsource')
    op.alter_column('projects', 'priority',
               existing_type=sa.VARCHAR(length=50),
               type_=project_priority_enum,
               existing_nullable=True,
               postgresql_using='priority::projectpriority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'priority',
               existing_type=sa.Enum('URGENT', 'HIGH', 'MEDIUM', 'LOW', 'NONE', name='projectpriority'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('projects', 'source',
               existing_type=sa.Enum('NATIVE', 'JIRA', 'LINEAR', 'GITHUB', name='projectsource'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'native'::character varying"))
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('DRAFT', 'PLANNING', 'ACTIVE', 'COMPLETED', 'ARCHIVED', 'BACKLOG', name='projectstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
