"""refactor_project_properties_table

Revision ID: c38b7aac933d
Revises: becefec2b22a
Create Date: 2026-01-13 12:01:19.838993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c38b7aac933d'
down_revision: Union[str, Sequence[str], None] = 'becefec2b22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('project', 'issue', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_entity_id'), 'properties', ['entity_id'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.drop_column('projects', 'deliverables')
    op.drop_column('projects', 'budget')
    op.drop_column('projects', 'integration_metadata')
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'milestones')
    op.drop_column('projects', 'stakeholders')
    op.drop_column('projects', 'objectives')
    op.drop_column('projects', 'purpose')
    op.drop_column('projects', 'stats')
    op.drop_column('projects', 'timeline')
    op.drop_column('projects', 'target_date')
    op.drop_column('projects', 'resources')
    op.drop_column('projects', 'labels')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'team_members')
    op.drop_column('projects', 'scope')
    op.drop_column('projects', 'teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('teams', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('scope', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('team_members', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('labels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('resources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('target_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('timeline', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('stats', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('purpose', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('objectives', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('stakeholders', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('milestones', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('priority', postgresql.ENUM('urgent', 'high', 'medium', 'low', 'none', name='projectpriority'), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('integration_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('budget', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('deliverables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_entity_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
