"""Added additional necessary fields to the project model and removed project intent, which is redundant.

Revision ID: dd225d0148a3
Revises: 800de23fe530
Create Date: 2025-12-12 08:23:05.596363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd225d0148a3'
down_revision: Union[str, Sequence[str], None] = '800de23fe530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_intents_intent_id'), table_name='project_intents')
    op.drop_table('project_intents')
    op.add_column('projects', sa.Column('purpose', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('objectives', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('scope', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('deliverables', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('timeline', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('budget', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('stakeholders', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('team_members', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'team_members')
    op.drop_column('projects', 'stakeholders')
    op.drop_column('projects', 'budget')
    op.drop_column('projects', 'timeline')
    op.drop_column('projects', 'deliverables')
    op.drop_column('projects', 'scope')
    op.drop_column('projects', 'objectives')
    op.drop_column('projects', 'purpose')
    op.create_table('project_intents',
    sa.Column('intent_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('constraints', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deliverables', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timeline_hints', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extracted_goals', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('project_intents_project_id_fkey')),
    sa.PrimaryKeyConstraint('intent_id', name=op.f('project_intents_pkey'))
    )
    op.create_index(op.f('ix_project_intents_intent_id'), 'project_intents', ['intent_id'], unique=False)
    # ### end Alembic commands ###
